### ISSUE TITLE
/api/graph/data respond with 502

### ISSUE THREAD

**Issue by panda87** [k8spacket/k8spacket#53]
Hey

I'm trying to set the chart and everything looks OK but the fact that querying the `/nodegraph/api/graph/data` endpoint responds w/ 502
The other API endpoints work OK including the /metrics that I can see all the data collected from the ds agents.

Can you please help this out?

**Comment by k8spacket** [comment]
Hi @panda87 

Could you share logs and describe info from daemonset?

Logs:
```
kubectl -n k8spacket logs <k8spacket-pod-name>
```

Describe pod:
```
kubectl -n k8spacket describe pod <k8spacket-pod-name>
```

Could you try to call the endpoint directly? 
```
kubectl run --rm -it --tty mycurl --image=curlimages/curl --restart=Never -- http://k8spacket.k8spacket.svc.cluster.local:8080/nodegraph/api/graph/data
```
The result should be similar to:
```
{"nodes":[{"id":"192.168.1.46","title":"N/A","subTitle":"192.168.1.46","mainStat":"all: N/A","secondaryStat":"persistent: N/A","arc__1":0,"arc__2":0,"arc__3":0},{"id":"10.100.33.29","title":"svc.proxy-app","subTitle":"10.100.33.29"
...
```

If the problem is visible on Grafana, share the Node Graph API datasource configuration. It should look like this one:

<img width="1365" alt="image" src="https://github.com/k8spacket/k8spacket/assets/95187481/1d06f1ac-67e2-402f-8ca2-372fa58c56eb">

---
If you have a problem with configuration, you can check the example on killercoda: https://killercoda.com/k8spacket/scenario/k8spacket

**Comment by panda87** [comment]
Just for alignment, am running 10s of agents. When fetching data from the k8spacket `service` should I expect to see a collection of data from a certain agent or all agents?

**Comment by k8spacket** [comment]
You should get a response from all agents.

When you call one agent, the agent calls all agents and aggregate response

Is there an option, in your cluster configuration, that one agent can't call another? 🤔

**Comment by panda87** [comment]
That communication should be allowed, especially when I run `/metrics` on the svc record and can see the data collected.
What else do you think I can check?
The `logs` + `describe` print the relevant data

**Comment by k8spacket** [comment]
The case with an unavailable agent on another node is still in the game.

The `/metrics` endpoint doesn't return data from all agents, only from called one, because Prometheus can collect metrics from every agent.

Yo can try to call another agent directly

1. Get agent IP:
```
k -n k8spacket get pods -owide
NAME              READY   STATUS    RESTARTS   AGE     IP           NODE           NOMINATED NODE   READINESS GATES
k8spacket-2vv62   1/1     Running   0          2m36s   172.30.1.2   controlplane   <none>           <none>
k8spacket-bph2z   1/1     Running   0          2m36s   172.30.2.2   node01         <none>           <none>
```
2. Call `k8spacket-bph2z` from `k8spacket-2vv62`
```
k -n k8spacket exec -it k8spacket-bph2z -- wget -O - http://172.30.1.2:6676/nodegraph/connections
```
3. Should return sth like
```
[{"src":"172.30.1.2","srcName":"node.controlplane","srcNamespace":"N/A","dst":"10.96.0.1","dstName":"svc.kubernetes","dstNamespace":"default","connCount":7,"connPersistent":1,"bytesSent":12675,"bytesReceived":212478,"duration":101650,"maxDuration":100816,"lastSeen":"2024-05-26T15:50:54.823312205Z"},{"src":"172.30.1.2","srcName":"node.controlplane","srcNamespace":"N/A","dst ...
```

---

Could you confirm that all agents have Status=Running and Ready=`1/1`?
```
k -n k8spacket get pods
```

**Comment by k8spacket** [comment]
Hi @panda87 

Yes, I think k8spacket should know how to omit agents without `status.phase=Running` and I've added this knowledge to the next version. See https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/values.yaml#L60

Now you can select agents by `fieldSelector` and `labelSelector`.

It would be nice to get feedback from you about this feature.
What you need to do is:

1. upgrade helm repo
```
helm repo update k8spacket
```

2. Reinstall k8spacket chart
```
helm upgrade --install k8spacket --namespace k8spacket k8spacket/k8spacket --create-namespace
```

**Comment by panda87** [comment]
Works like a charm!
Thank you @k8spacket
