### ISSUE TITLE
Wiz security tool classifies k8spacket as high security risk: Dynamic linker executed as process

### ISSUE THREAD

**Issue by bonapeti** [k8spacket/k8spacket#59]
Hi

We use WIZ for scanning for vulnerabilities and k8spacket was classified as a risk because 'Dynamic linker executed as process'.

Details:
Dynamic linker executed as a process directly. Typically the loader is loaded as a shared object while a process is starting and its purpose is to load and link shared libraries during the execution of a program, resolving external symbols and enabling dynamic linking in the Linux operating system. Execution of the dynamic linker with a given image path of an binary image will result with the loader running as the given image.

Command line:
ld-linux-x86-64.so.2 --argv0 ./k8spacket --preload /lib/libgcompat.so.0  -- /home/k8spacket/k8spacket

Can you please share why k8spacket is executed this way?

**Comment by k8spacket** [comment]
Hi @bonapeti 

k8spacket uses the Golang plugin approach (https://pkg.go.dev/plugin) where `nodegraph` and `tls-parser` are built as plugins and provided to the k8spacket base application from the outside. 
- plugins loader: https://github.com/k8spacket/k8spacket/blob/master/plugins/loader.go
- plugin supplier 
  - https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/templates/daemonset.yaml#L49
  - https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/values.yaml#L61

Using go-plugins requires the use of dynamic linking. (https://github.com/golang/go/issues/19569#issuecomment-291955357)

Additionally, k8spacket is compiled with a golang image with GNU C Library and runs with an Alpine image with Musl C Library. That's why `libgcompat` is preloaded to run glibc binaries on Alpine.

```
strace ./k8spacket

execve("./k8spacket", ["./k8spacket"], 0xffffee005340 /* 6 vars */) = 0
set_tid_address(0xffff8302e890)         = 22
brk(NULL)                               = 0x1333e000
brk(0x1333f000)                         = 0x1333f000
readlinkat(AT_FDCWD, "/proc/self/exe", "/home/k8spacket/k8spacket", 4096) = 25
execve("/lib/ld-musl-aarch64.so.1", ["ld-linux-aarch64.so.1", "--argv0", "./k8spacket", "--preload", "/lib/libgcompat.so.0 ", "--", "/home/k8spacket/k8spacket"], 0xfffff4a9b568 /* 6 vars */) = 0
set_tid_address(0xffff9c70ce78)         = 22
```

Anyway, thanks for pointing it out. I need to think about it deeply. k8spacket shouldn't use Alpine as a final image or using plugins was not the best idea because it brings more problems than advantages.

**Comment by k8spacket** [comment]
Hi @bonapeti 

k8spacket no longer uses go-plugins since version 2.1.0 - https://github.com/k8spacket/k8spacket/releases/tag/v2.1.0
I'm going to close that issue.
