### ISSUE TITLE
Not seeing resource name prepend to domain for AWS Services

### ISSUE THREAD

**Issue by shail-jaiswar24** [k8spacket/k8spacket#66]
@k8spacket We have implemented K8spacket in our EKS cluster and it is working as expected.

But the only issue we have observed is it's not able to figure out Domain or actual resource for below AWS Services:

AWS Services:

```
Dyanmodb
SQS
SMTP
SNS
mediaconnect
medialive
mediapackage
ssm
```
It's only showing below domain excluding resource name which can be prepended to it:

```
dynamodb.ap-south-1.amazonaws.com
sqs.ap-south-1.amazonaws.com
```

Setup Details:

```
EKS Version: 1.28
Kernel Version: 5.10.214-202.855.amzn2.x86_64
k8spacket version:           image: "docker.io/k8spacket/k8spacket:2.0.4"
OS Details: 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
Additional Details wrt bpf:
```

```
[root@IPAddress bin]# $ ls /sys/kernel/btf/vmlinux
bash: $: command not found
[root@IPAddress bin]# ls /sys/kernel/btf/vmlinux
/sys/kernel/btf/vmlinux
[root@IPAddress bin]# egrep '(CONFIG_BPF|CONFIG_BPF_SYSCALL|CONFIG_BPF_JIT|CONFIG_BPF_EVENTS)=' /boot/config-$(uname -r)
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_BPF_EVENTS=y
[root@IPAddress bin]# egrep '(CONFIG_HAVE_BPF_JIT|CONFIG_HAVE_EBPF_JIT)=' /boot/config-$(uname -r)
CONFIG_HAVE_EBPF_JIT=y
[root@IPAddress bin]# cat /boot/config-$(uname -r) | grep CONFIG_IKHEADERS
CONFIG_IKHEADERS=m
```

Let us know if any capabilities has to be included in Helm or is this the expectation

**Comment by k8spacket** [comment]
Hi @shail-jaiswar24 

k8spacket monitors TCP protocol only.
- `media*` AWS services have been responsible for sending streams, so they use UDP protocol I supposed.
- `sns` and `smtp` AWS services establish persistent connections probably. This is one connection established for a long time keeping open for further communications from the client. k8spacket waits for the `TCP_CLOSE` signal before sending the connection metrics to the userspace. You could not see it, because this connection is still established. I have this on my roadmap to make it more reliable.

**Comment by shail248** [comment]
Hi @k8spacket 

Thanks for an update.

Also wrt dynamodb even though it's TCP but Dynamodb API https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.LowLevelAPI.html#Programming.LowLevelAPI.RequestFormat doesn't keep Table name in Host section of request instead it's in Payload.

Is it possible to have it prefix to Domain when service is Dynamodb, haven't thought from security point.

**Comment by k8spacket** [comment]
Hi @shail-jaiswar24 , @shail248 

Short answer: k8spacket cannot show the content of the body and cannot prefix the domain from the payload.

I assumed you mentioned the `k8spacket - node graph` dashboard, but now I'm unsure. Which dashboard do you observe?
But, let's describe it for both

---

***`k8spacket - node graph` - this dashboard is about TCP packets, so there is no even information about a domain name***

after making a curl request:
```
$ curl https://dynamodb.ap-south-1.amazonaws.com -v
* Host dynamodb.ap-south-1.amazonaws.com:443 was resolved.
* IPv6: (none)
* IPv4: 35.71.100.1
*   Trying 35.71.100.1:443...
* Connected to dynamodb.ap-south-1.amazonaws.com (35.71.100.1) port 443
...
```
You can see only IP and whois information provided by the tool https://github.com/likexian/whois

<img width="385" alt="image" src="https://github.com/user-attachments/assets/034ed165-e786-4d64-b3a8-5f5041a03906">

---


***`k8spacket - TLS certificate expiration` and `k8spacket - TLS connections & certificates` are about TLS handshake process***

Here k8spacket doesn't get information from the payload, because it can't decrypt the encrypted connection. It collects information from the TLS handshake process, where the domain is stored in the Client Hello Extensions step, called `Server Name`. See https://tls13.xargs.org/#client-hello/annotated 

<img width="318" alt="image" src="https://github.com/user-attachments/assets/368a9737-70e7-4cee-a4b7-78e7b262c05e">

<img width="2236" alt="image" src="https://github.com/user-attachments/assets/6739d0ea-f005-4cd4-8686-683560be0904">

**Comment by k8spacket** [comment]
Hi @shail248 , @shail-jaiswar24 

I hope, my comment covered your question. I'm going to close the issue. If you have more questions, feel free to open it again.
